name: 'Publish package to internal CodeArtifact'
description: 'Publishes the current package to an internal CodeArtifact on a pre-release tag'
runs:
  using: 'composite'
  steps:
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: 14.x

    - name: Define new version suffix
      id: vars
      run: echo "::set-output name=version_suffix::-next-build.$(git rev-parse --short HEAD)"
      shell: bash

    - run: INPUT_PATH=${{ github.workspace }} INPUT_SUFFIX=${{ steps.vars.outputs.version_suffix }} node ${{ github.action_path }}/index.mjs
      shell: bash
