name: Build, lint and test

on:
  pull_request:
    branches:
      - main
      - test-commit-hook
  push:
    branches:
      - main

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  build:
    uses: cloudscape-design/.github/.github/workflows/build-lint-test.yml@commit-hook
